[package]
name = "private-bb-dispatch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bazel-remote-apis = "0.27.0"
clap = { version = "4.6.4", features = ["derive"] }
futures-util = "0.3.33"
hyper-util = "0.1.20"
prost = "0.14.4"
rayon = "1.12.0"
reapi = { path = "../../lib/reapi" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.14.6", features = ["transport", "tls-ring", "tls-native-roots"] }
tower = { version = "0.5.3", features = ["util"] }
uuid = { version = "1.24.0", features = ["v4"] }
walkdir = "2.5.0"
