// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/configuration/bb_completed_actions_ingester/bb_completed_actions_ingester.proto

package bb_completed_actions_ingester

import (
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	elasticsearch "github.com/meroton/buildbar/proto/configuration/elasticsearch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                     protoimpl.MessageState             `protogen:"open.v1"`
	GrpcServers               []*grpc.ServerConfiguration        `protobuf:"bytes,1,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	ContentAddressableStorage *blobstore.BlobAccessConfiguration `protobuf:"bytes,2,opt,name=content_addressable_storage,json=contentAddressableStorage,proto3" json:"content_addressable_storage,omitempty"`
	MaximumMessageSizeBytes   int64                              `protobuf:"varint,3,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	Global                    *global.Configuration              `protobuf:"bytes,4,opt,name=global,proto3" json:"global,omitempty"`
	Elasticsearch             *elasticsearch.ClientConfiguration `protobuf:"bytes,5,opt,name=elasticsearch,proto3" json:"elasticsearch,omitempty"`
	ElasticsearchIndex        string                             `protobuf:"bytes,6,opt,name=elasticsearch_index,json=elasticsearchIndex,proto3" json:"elasticsearch_index,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetContentAddressableStorage() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.ContentAddressableStorage
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetElasticsearch() *elasticsearch.ClientConfiguration {
	if x != nil {
		return x.Elasticsearch
	}
	return nil
}

func (x *ApplicationConfiguration) GetElasticsearchIndex() string {
	if x != nil {
		return x.ElasticsearchIndex
	}
	return ""
}

var File_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto protoreflect.FileDescriptor

const file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDesc = "" +
	"\n" +
	"Uproto/configuration/bb_completed_actions_ingester/bb_completed_actions_ingester.proto\x124buildbar.configuration.bb_completed_actions_ingester\x1a1pkg/proto/configuration/blobstore/blobstore.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\x1a5proto/configuration/elasticsearch/elasticsearch.proto\"\x82\x04\n" +
	"\x18ApplicationConfiguration\x12T\n" +
	"\fgrpc_servers\x18\x01 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12z\n" +
	"\x1bcontent_addressable_storage\x18\x02 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x19contentAddressableStorage\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x03 \x01(\x03R\x17maximumMessageSizeBytes\x12E\n" +
	"\x06global\x18\x04 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12_\n" +
	"\relasticsearch\x18\x05 \x01(\v29.buildbar.configuration.elasticsearch.ClientConfigurationR\relasticsearch\x12/\n" +
	"\x13elasticsearch_index\x18\x06 \x01(\tR\x12elasticsearchIndexBOZMgithub.com/meroton/buildbar/proto/configuration/bb_completed_actions_ingesterb\x06proto3"

var (
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescOnce sync.Once
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescData []byte
)

func file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescGZIP() []byte {
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescOnce.Do(func() {
		file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDesc), len(file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDesc)))
	})
	return file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDescData
}

var file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),          // 0: buildbar.configuration.bb_completed_actions_ingester.ApplicationConfiguration
	(*grpc.ServerConfiguration)(nil),          // 1: buildbarn.configuration.grpc.ServerConfiguration
	(*blobstore.BlobAccessConfiguration)(nil), // 2: buildbarn.configuration.blobstore.BlobAccessConfiguration
	(*global.Configuration)(nil),              // 3: buildbarn.configuration.global.Configuration
	(*elasticsearch.ClientConfiguration)(nil), // 4: buildbar.configuration.elasticsearch.ClientConfiguration
}
var file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_depIdxs = []int32{
	1, // 0: buildbar.configuration.bb_completed_actions_ingester.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	2, // 1: buildbar.configuration.bb_completed_actions_ingester.ApplicationConfiguration.content_addressable_storage:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	3, // 2: buildbar.configuration.bb_completed_actions_ingester.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	4, // 3: buildbar.configuration.bb_completed_actions_ingester.ApplicationConfiguration.elasticsearch:type_name -> buildbar.configuration.elasticsearch.ClientConfiguration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_init()
}
func file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_init() {
	if File_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDesc), len(file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_goTypes,
		DependencyIndexes: file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_depIdxs,
		MessageInfos:      file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_msgTypes,
	}.Build()
	File_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto = out.File
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_goTypes = nil
	file_proto_configuration_bb_completed_actions_ingester_bb_completed_actions_ingester_proto_depIdxs = nil
}
