load("//tools:rust.bzl", "rust_binary", "rust_doc_test", "rust_library")

rust_library(
    name = "re_memoize_lib",
    crate_name = "re_memoize",
    srcs = [
        "src/error.rs",
        "src/lib.rs",
        "src/run.rs",
    ],
    edition = "2024",
    visibility = ["//cmd/integration_test:__pkg__"],
    deps = [
        "//lib/re_storage",
        "//lib/reapi",
        "@crates//:bazel-remote-apis",
        "@crates//:prost",
        "@crates//:thiserror",
        "@crates//:tokio",
    ],
)

rust_doc_test(
    name = "re_memoize_doc_test",
    crate = ":re_memoize_lib",
)

rust_binary(
    name = "re-memoize",
    srcs = ["src/main.rs"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        ":re_memoize_lib",
        "//lib/re_storage",
        "@crates//:clap",
        "@crates//:tokio",
    ],
)
