// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/configuration/bb_slow_generic_runner/bb_slow_generic_runner.proto

package bb_slow_generic_runner

import (
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	BuildDirectoryPath string                      `protobuf:"bytes,1,opt,name=build_directory_path,json=buildDirectoryPath,proto3" json:"build_directory_path,omitempty"`
	GrpcServers        []*grpc.ServerConfiguration `protobuf:"bytes,2,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	Global             *global.Configuration       `protobuf:"bytes,3,opt,name=global,proto3" json:"global,omitempty"`
	RunCommandWrapper  []string                    `protobuf:"bytes,4,rep,name=run_command_wrapper,json=runCommandWrapper,proto3" json:"run_command_wrapper,omitempty"`
	ReadinessCommand   []string                    `protobuf:"bytes,5,rep,name=readiness_command,json=readinessCommand,proto3" json:"readiness_command,omitempty"`
	CleanerCommand     []string                    `protobuf:"bytes,6,rep,name=cleaner_command,json=cleanerCommand,proto3" json:"cleaner_command,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetBuildDirectoryPath() string {
	if x != nil {
		return x.BuildDirectoryPath
	}
	return ""
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetRunCommandWrapper() []string {
	if x != nil {
		return x.RunCommandWrapper
	}
	return nil
}

func (x *ApplicationConfiguration) GetReadinessCommand() []string {
	if x != nil {
		return x.ReadinessCommand
	}
	return nil
}

func (x *ApplicationConfiguration) GetCleanerCommand() []string {
	if x != nil {
		return x.CleanerCommand
	}
	return nil
}

var File_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto protoreflect.FileDescriptor

const file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDesc = "" +
	"\n" +
	"Gproto/configuration/bb_slow_generic_runner/bb_slow_generic_runner.proto\x12-buildbar.configuration.bb_slow_generic_runner\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\"\xef\x02\n" +
	"\x18ApplicationConfiguration\x120\n" +
	"\x14build_directory_path\x18\x01 \x01(\tR\x12buildDirectoryPath\x12T\n" +
	"\fgrpc_servers\x18\x02 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12E\n" +
	"\x06global\x18\x03 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12.\n" +
	"\x13run_command_wrapper\x18\x04 \x03(\tR\x11runCommandWrapper\x12+\n" +
	"\x11readiness_command\x18\x05 \x03(\tR\x10readinessCommand\x12'\n" +
	"\x0fcleaner_command\x18\x06 \x03(\tR\x0ecleanerCommandBHZFgithub.com/meroton/buildbar/proto/configuration/bb_slow_generic_runnerb\x06proto3"

var (
	file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescOnce sync.Once
	file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescData []byte
)

func file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescGZIP() []byte {
	file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescOnce.Do(func() {
		file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDesc), len(file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDesc)))
	})
	return file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDescData
}

var file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil), // 0: buildbar.configuration.bb_slow_generic_runner.ApplicationConfiguration
	(*grpc.ServerConfiguration)(nil), // 1: buildbarn.configuration.grpc.ServerConfiguration
	(*global.Configuration)(nil),     // 2: buildbarn.configuration.global.Configuration
}
var file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_depIdxs = []int32{
	1, // 0: buildbar.configuration.bb_slow_generic_runner.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	2, // 1: buildbar.configuration.bb_slow_generic_runner.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_init() }
func file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_init() {
	if File_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDesc), len(file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_goTypes,
		DependencyIndexes: file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_depIdxs,
		MessageInfos:      file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_msgTypes,
	}.Build()
	File_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto = out.File
	file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_goTypes = nil
	file_proto_configuration_bb_slow_generic_runner_bb_slow_generic_runner_proto_depIdxs = nil
}
