// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.1
// source: proto/configuration/elasticsearch/elasticsearch.proto

package elasticsearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses     []string           `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Credentials   *ClientCredentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	SkipVerifyTls bool               `protobuf:"varint,3,opt,name=skip_verify_tls,json=skipVerifyTls,proto3" json:"skip_verify_tls,omitempty"`
}

func (x *ClientConfiguration) Reset() {
	*x = ClientConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfiguration) ProtoMessage() {}

func (x *ClientConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfiguration.ProtoReflect.Descriptor instead.
func (*ClientConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfiguration) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ClientConfiguration) GetCredentials() *ClientCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ClientConfiguration) GetSkipVerifyTls() bool {
	if x != nil {
		return x.SkipVerifyTls
	}
	return false
}

type ClientCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Credentials:
	//
	//	*ClientCredentials_BasicAuth
	//	*ClientCredentials_ApiKey
	//	*ClientCredentials_ServiceToken
	Credentials isClientCredentials_Credentials `protobuf_oneof:"credentials"`
}

func (x *ClientCredentials) Reset() {
	*x = ClientCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredentials) ProtoMessage() {}

func (x *ClientCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredentials.ProtoReflect.Descriptor instead.
func (*ClientCredentials) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{1}
}

func (m *ClientCredentials) GetCredentials() isClientCredentials_Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (x *ClientCredentials) GetBasicAuth() *ClientCredentials_HttpBasicAuth {
	if x, ok := x.GetCredentials().(*ClientCredentials_BasicAuth); ok {
		return x.BasicAuth
	}
	return nil
}

func (x *ClientCredentials) GetApiKey() string {
	if x, ok := x.GetCredentials().(*ClientCredentials_ApiKey); ok {
		return x.ApiKey
	}
	return ""
}

func (x *ClientCredentials) GetServiceToken() string {
	if x, ok := x.GetCredentials().(*ClientCredentials_ServiceToken); ok {
		return x.ServiceToken
	}
	return ""
}

type isClientCredentials_Credentials interface {
	isClientCredentials_Credentials()
}

type ClientCredentials_BasicAuth struct {
	BasicAuth *ClientCredentials_HttpBasicAuth `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

type ClientCredentials_ApiKey struct {
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type ClientCredentials_ServiceToken struct {
	ServiceToken string `protobuf:"bytes,3,opt,name=service_token,json=serviceToken,proto3,oneof"`
}

func (*ClientCredentials_BasicAuth) isClientCredentials_Credentials() {}

func (*ClientCredentials_ApiKey) isClientCredentials_Credentials() {}

func (*ClientCredentials_ServiceToken) isClientCredentials_Credentials() {}

type ClientCredentials_HttpBasicAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ClientCredentials_HttpBasicAuth) Reset() {
	*x = ClientCredentials_HttpBasicAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCredentials_HttpBasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredentials_HttpBasicAuth) ProtoMessage() {}

func (x *ClientCredentials_HttpBasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredentials_HttpBasicAuth.ProtoReflect.Descriptor instead.
func (*ClientCredentials_HttpBasicAuth) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientCredentials_HttpBasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientCredentials_HttpBasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_configuration_elasticsearch_elasticsearch_proto protoreflect.FileDescriptor

var file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc = []byte{
	0x0a, 0x35, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x2f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61,
	0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0xb6, 0x01,
	0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x62, 0x61, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x26,
	0x0a, 0x0f, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x6b, 0x69, 0x70, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x54, 0x6c, 0x73, 0x22, 0x95, 0x02, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x66, 0x0a, 0x0a,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x45, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x19, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12,
	0x25, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x47, 0x0a, 0x0d, 0x48, 0x74, 0x74, 0x70, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42,
	0x0d, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x3f,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x72,
	0x6f, 0x74, 0x6f, 0x6e, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescOnce sync.Once
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData = file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc
)

func file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP() []byte {
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescOnce.Do(func() {
		file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData)
	})
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData
}

var file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes = []interface{}{
	(*ClientConfiguration)(nil),             // 0: buildbar.configuration.elasticsearch.ClientConfiguration
	(*ClientCredentials)(nil),               // 1: buildbar.configuration.elasticsearch.ClientCredentials
	(*ClientCredentials_HttpBasicAuth)(nil), // 2: buildbar.configuration.elasticsearch.ClientCredentials.HttpBasicAuth
}
var file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs = []int32{
	1, // 0: buildbar.configuration.elasticsearch.ClientConfiguration.credentials:type_name -> buildbar.configuration.elasticsearch.ClientCredentials
	2, // 1: buildbar.configuration.elasticsearch.ClientCredentials.basic_auth:type_name -> buildbar.configuration.elasticsearch.ClientCredentials.HttpBasicAuth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_configuration_elasticsearch_elasticsearch_proto_init() }
func file_proto_configuration_elasticsearch_elasticsearch_proto_init() {
	if File_proto_configuration_elasticsearch_elasticsearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCredentials_HttpBasicAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ClientCredentials_BasicAuth)(nil),
		(*ClientCredentials_ApiKey)(nil),
		(*ClientCredentials_ServiceToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes,
		DependencyIndexes: file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs,
		MessageInfos:      file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes,
	}.Build()
	File_proto_configuration_elasticsearch_elasticsearch_proto = out.File
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc = nil
	file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes = nil
	file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs = nil
}
