// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/configuration/elasticsearch/elasticsearch.proto

package elasticsearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Credentials   *ClientCredentials     `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	SkipVerifyTls bool                   `protobuf:"varint,3,opt,name=skip_verify_tls,json=skipVerifyTls,proto3" json:"skip_verify_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfiguration) Reset() {
	*x = ClientConfiguration{}
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfiguration) ProtoMessage() {}

func (x *ClientConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfiguration.ProtoReflect.Descriptor instead.
func (*ClientConfiguration) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfiguration) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ClientConfiguration) GetCredentials() *ClientCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ClientConfiguration) GetSkipVerifyTls() bool {
	if x != nil {
		return x.SkipVerifyTls
	}
	return false
}

type ClientCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*ClientCredentials_BasicAuth
	//	*ClientCredentials_ApiKey
	//	*ClientCredentials_ServiceToken
	Credentials   isClientCredentials_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCredentials) Reset() {
	*x = ClientCredentials{}
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredentials) ProtoMessage() {}

func (x *ClientCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredentials.ProtoReflect.Descriptor instead.
func (*ClientCredentials) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{1}
}

func (x *ClientCredentials) GetCredentials() isClientCredentials_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ClientCredentials) GetBasicAuth() *ClientCredentials_HttpBasicAuth {
	if x != nil {
		if x, ok := x.Credentials.(*ClientCredentials_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

func (x *ClientCredentials) GetApiKey() string {
	if x != nil {
		if x, ok := x.Credentials.(*ClientCredentials_ApiKey); ok {
			return x.ApiKey
		}
	}
	return ""
}

func (x *ClientCredentials) GetServiceToken() string {
	if x != nil {
		if x, ok := x.Credentials.(*ClientCredentials_ServiceToken); ok {
			return x.ServiceToken
		}
	}
	return ""
}

type isClientCredentials_Credentials interface {
	isClientCredentials_Credentials()
}

type ClientCredentials_BasicAuth struct {
	BasicAuth *ClientCredentials_HttpBasicAuth `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

type ClientCredentials_ApiKey struct {
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type ClientCredentials_ServiceToken struct {
	ServiceToken string `protobuf:"bytes,3,opt,name=service_token,json=serviceToken,proto3,oneof"`
}

func (*ClientCredentials_BasicAuth) isClientCredentials_Credentials() {}

func (*ClientCredentials_ApiKey) isClientCredentials_Credentials() {}

func (*ClientCredentials_ServiceToken) isClientCredentials_Credentials() {}

type ClientCredentials_HttpBasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCredentials_HttpBasicAuth) Reset() {
	*x = ClientCredentials_HttpBasicAuth{}
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCredentials_HttpBasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCredentials_HttpBasicAuth) ProtoMessage() {}

func (x *ClientCredentials_HttpBasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCredentials_HttpBasicAuth.ProtoReflect.Descriptor instead.
func (*ClientCredentials_HttpBasicAuth) Descriptor() ([]byte, []int) {
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientCredentials_HttpBasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientCredentials_HttpBasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_configuration_elasticsearch_elasticsearch_proto protoreflect.FileDescriptor

const file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc = "" +
	"\n" +
	"5proto/configuration/elasticsearch/elasticsearch.proto\x12$buildbar.configuration.elasticsearch\"\xb6\x01\n" +
	"\x13ClientConfiguration\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12Y\n" +
	"\vcredentials\x18\x02 \x01(\v27.buildbar.configuration.elasticsearch.ClientCredentialsR\vcredentials\x12&\n" +
	"\x0fskip_verify_tls\x18\x03 \x01(\bR\rskipVerifyTls\"\x95\x02\n" +
	"\x11ClientCredentials\x12f\n" +
	"\n" +
	"basic_auth\x18\x01 \x01(\v2E.buildbar.configuration.elasticsearch.ClientCredentials.HttpBasicAuthH\x00R\tbasicAuth\x12\x19\n" +
	"\aapi_key\x18\x02 \x01(\tH\x00R\x06apiKey\x12%\n" +
	"\rservice_token\x18\x03 \x01(\tH\x00R\fserviceToken\x1aG\n" +
	"\rHttpBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB\r\n" +
	"\vcredentialsB?Z=github.com/meroton/buildbar/proto/configuration/elasticsearchb\x06proto3"

var (
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescOnce sync.Once
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData []byte
)

func file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescGZIP() []byte {
	file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescOnce.Do(func() {
		file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc), len(file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc)))
	})
	return file_proto_configuration_elasticsearch_elasticsearch_proto_rawDescData
}

var file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes = []any{
	(*ClientConfiguration)(nil),             // 0: buildbar.configuration.elasticsearch.ClientConfiguration
	(*ClientCredentials)(nil),               // 1: buildbar.configuration.elasticsearch.ClientCredentials
	(*ClientCredentials_HttpBasicAuth)(nil), // 2: buildbar.configuration.elasticsearch.ClientCredentials.HttpBasicAuth
}
var file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs = []int32{
	1, // 0: buildbar.configuration.elasticsearch.ClientConfiguration.credentials:type_name -> buildbar.configuration.elasticsearch.ClientCredentials
	2, // 1: buildbar.configuration.elasticsearch.ClientCredentials.basic_auth:type_name -> buildbar.configuration.elasticsearch.ClientCredentials.HttpBasicAuth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_configuration_elasticsearch_elasticsearch_proto_init() }
func file_proto_configuration_elasticsearch_elasticsearch_proto_init() {
	if File_proto_configuration_elasticsearch_elasticsearch_proto != nil {
		return
	}
	file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientCredentials_BasicAuth)(nil),
		(*ClientCredentials_ApiKey)(nil),
		(*ClientCredentials_ServiceToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc), len(file_proto_configuration_elasticsearch_elasticsearch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes,
		DependencyIndexes: file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs,
		MessageInfos:      file_proto_configuration_elasticsearch_elasticsearch_proto_msgTypes,
	}.Build()
	File_proto_configuration_elasticsearch_elasticsearch_proto = out.File
	file_proto_configuration_elasticsearch_elasticsearch_proto_goTypes = nil
	file_proto_configuration_elasticsearch_elasticsearch_proto_depIdxs = nil
}
