name: bb-kv-ci
on:
  pull_request:
    paths:
      - cmd/bb_kv/**
      - .github/workflows/bb-kv-ci.yaml
  push:
    branches:
      - main
    paths:
      - cmd/bb_kv/**
      - .github/workflows/bb-kv-ci.yaml
defaults:
  run:
    working-directory: cmd/bb_kv
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: rustup show
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: cmd/bb_kv
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --locked -- -Dwarnings
      - name: Build
        run: cargo build --all-targets --locked
      - name: Test
        run: cargo test --workspace --locked
