{
   "jobs": {
      "build_and_test": {
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "name": "Check out source code",
               "uses": "actions/checkout@v1"
            },
            {
               "name": "Installing Bazel",
               "run": "v=$(cat .bazelversion) && curl -L https://github.com/bazelbuild/bazel/releases/download/${v}/bazel-${v}-linux-x86_64 > ~/bazel && chmod +x ~/bazel && echo ~ >> ${GITHUB_PATH}"
            },
            {
               "name": "Bazel mod tidy",
               "run": "bazel mod tidy"
            },
            {
               "name": "Gazelle",
               "run": "find proto -name BUILD.bazel -delete &&\nbazel run //:gazelle &&\ntools/append_proto_write_source_targets.sh\n"
            },
            {
               "name": "Buildifier",
               "run": "bazel run //:buildifier_fix"
            },
            {
               "name": "Gofmt",
               "run": "bazel run @cc_mvdan_gofumpt//:gofumpt -- -w -extra $(pwd)"
            },
            {
               "name": "Clang format",
               "run": "find . -name '*.proto' -exec bazel run @llvm_toolchain_llvm//:bin/clang-format -- -i {} +"
            },
            {
               "name": "Test style conformance",
               "run": "git add . && git diff --exit-code HEAD --"
            },
            {
               "name": "Golint",
               "run": "bazel run @org_golang_x_lint//golint -- -set_exit_status $(pwd)/..."
            },
            {
               "name": "linux_amd64: build and test",
               "run": "bazel test --test_output=errors --platforms=@rules_go//go/toolchain:linux_amd64 //..."
            },
            {
               "name": "linux_amd64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:linux_amd64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "linux_amd64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.linux_amd64",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "linux_386: build and test",
               "run": "bazel test --test_output=errors --platforms=@rules_go//go/toolchain:linux_386 //..."
            },
            {
               "name": "linux_386: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:linux_386 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "linux_386: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.linux_386",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "linux_arm: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:linux_arm //..."
            },
            {
               "name": "linux_arm: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:linux_arm //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "linux_arm: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.linux_arm",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "linux_arm64: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:linux_arm64 //..."
            },
            {
               "name": "linux_arm64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:linux_arm64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "linux_arm64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.linux_arm64",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "darwin_amd64: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:darwin_amd64 //..."
            },
            {
               "name": "darwin_amd64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:darwin_amd64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "darwin_amd64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.darwin_amd64",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "darwin_arm64: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:darwin_arm64 //..."
            },
            {
               "name": "darwin_arm64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:darwin_arm64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "darwin_arm64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.darwin_arm64",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "freebsd_amd64: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:freebsd_amd64 //cmd/bb_completed_actions_ingester"
            },
            {
               "name": "freebsd_amd64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester && bazel run --run_under cp --platforms=@rules_go//go/toolchain:freebsd_amd64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester"
            },
            {
               "name": "freebsd_amd64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.freebsd_amd64",
                  "path": "bb_completed_actions_ingester"
               }
            },
            {
               "name": "windows_amd64: build and test",
               "run": "bazel build --platforms=@rules_go//go/toolchain:windows_amd64 //..."
            },
            {
               "name": "windows_amd64: copy bb_completed_actions_ingester",
               "run": "rm -f bb_completed_actions_ingester.exe && bazel run --run_under cp --platforms=@rules_go//go/toolchain:windows_amd64 //cmd/bb_completed_actions_ingester $(pwd)/bb_completed_actions_ingester.exe"
            },
            {
               "name": "windows_amd64: upload bb_completed_actions_ingester",
               "uses": "actions/upload-artifact@v2-preview",
               "with": {
                  "name": "bb_completed_actions_ingester.windows_amd64",
                  "path": "bb_completed_actions_ingester.exe"
               }
            },
            {
               "env": {
                  "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
               },
               "name": "Install Docker credentials",
               "run": "echo \"${GITHUB_TOKEN}\" | docker login ghcr.io -u $ --password-stdin"
            },
            {
               "name": "Push container bb_completed_actions_ingester:bb_completed_actions_ingester",
               "run": "bazel run --stamp //cmd/bb_completed_actions_ingester:bb_completed_actions_ingester_container_push"
            }
         ]
      }
   },
   "name": "main",
   "on": {
      "push": {
         "branches": [
            "main"
         ]
      }
   }
}
